### PR TITLE
bugfix/T4T-837 Safari - Print icon activation triggers browser hang

### PR DESCRIPTION
**Pull request by kb-smarterbalanced**
T4T-837 Safari - Print icon activation triggers browser hang

Please review this - note that the "print" button still doesn't work in Safari, this is just to make sure the pdf is loading.

### CODE REVIEW

**Comment by ramacsh** [comment]
Tested the branch on local, and functionality is same as seen in Dev and QA using Safari Version 14.0.3, macOS Catalina Version 10.15.7. 

PDF loads on clicking Print Icon, and only the top of Page 1 is visible in Print Preview with a lot of whitespace between the preview section and the 'Print/Download/Close' buttons (see attached)
SafariLoadPDF

**Review by JJ-Muller — COMMENTED** [review]
@kb-smarterbalanced I believe the develop branch was updated after you cut the bugfix branch from it.  Did you get a chance to merge the develop branch onto your bugfix branch to ensure it was up to date with the latest updates? If not, please catch your bugfix branch up and push those changes. thank you!

**Comment by kb-smarterbalanced** [comment]
Updated to include merged develop. Please review again.

**Comment by ramacsh** [comment]
Pulled latest changes, and observe the same behavior with only top of Page 1 is visible in Print Preview.

**Comment by JJ-Muller** [comment]
@kb-smarterbalanced did you add updates to the .ts file also or is that from something else? Asking because I noticed there are now 2 files instead of 1 file changed in this update

**Comment by kb-smarterbalanced** [comment]
There were some formatting changes to the second file – I just added so my IDE would stop complaining. Sorry for any confusion.

Kristin

From: JJ-Muller ***@***.***>
Date: Friday, July 16, 2021 at 10:36 AM
To: SmarterApp/DL_DigitalLibrary2.0 ***@***.***>
Cc: Kristin Bradham ***@***.***>, Mention ***@***.***>
Subject: Re: [SmarterApp/DL_DigitalLibrary2.0] bugfix/T4T-837 Safari - Print icon activation triggers browser hang (#399)

@kb-smarterbalanced<https://github.com/kb-smarterbalanced> did you add updates to the .ts file also or is that from something else? Asking because I noticed there are now 2 files instead of 1 file changed in this update

**Comment by kb-smarterbalanced** [comment]
Shankar – thank you for reviewing. As I will be changing this functionality for Safari, I’m not going to address this for now because it will most likely not be what people see when they are on Safari.

Thanks,
Kristin

From: ramacsh ***@***.***>
Date: Friday, July 16, 2021 at 9:48 AM
To: SmarterApp/DL_DigitalLibrary2.0 ***@***.***>
Cc: Kristin Bradham ***@***.***>, Mention ***@***.***>
Subject: Re: [SmarterApp/DL_DigitalLibrary2.0] bugfix/T4T-837 Safari - Print icon activation triggers browser hang (#399)

Pulled latest changes, and observe the same behavior with only top of Page 1 is visible in Print Preview.

**Comment by JJ-Muller** [comment]
@kb-smarterbalanced that is great!  thank you

**Review by JJ-Muller — APPROVED** [review]

**Comment by kb-smarterbalanced** [comment]
Ipsita - new merge - please check 837 and 836

**Pull request merged**
